import type { SpeciesDef } from '../core/types';

// MVP roster: 12 wild species (arrive via lures) + 6 hybrids (eggs only).
// Each has a strong silhouette that survives mutation overlays and Giant scaling.
export const SPECIES: SpeciesDef[] = [
  {
    id: 'mossfrog', name: 'Mossfrog', traits: ['Amphibian', 'Grove', 'Tide'], rarity: 'common',
    activity: 'day', movement: 'hop', origin: 'wild',
    blurb: 'Grows a little garden on its back. Sings before it rains.',
    hint: 'Common wherever moss meets water.',
    eggColors: ['#7fbf6a', '#3f7a3a'],
  },
  {
    id: 'pebbleback', name: 'Pebbleback', traits: ['Reptile', 'Tide'], rarity: 'common',
    activity: 'day', movement: 'walk', origin: 'wild',
    blurb: 'Collects smooth stones on its shell. Never in a hurry.',
    hint: 'Something slow likes the smell of the river.',
    eggColors: ['#9aa7a0', '#5d6e68'],
  },
  {
    id: 'glowbeetle', name: 'Glowbeetle', traits: ['Insect', 'Grove'], rarity: 'common',
    activity: 'night', movement: 'scuttle', origin: 'wild',
    blurb: 'Its lantern brightens when it feels safe.',
    hint: 'A small light in the forest, after dark.',
    eggColors: ['#2f4a6e', '#c9f56a'],
  },
  {
    id: 'petalwing', name: 'Petalwing', traits: ['Insect', 'Bloom', 'Grove'], rarity: 'common',
    activity: 'day', movement: 'fly', origin: 'wild',
    blurb: 'Its wings are real petals. It replaces them every spring.',
    hint: 'Drawn to sweet things in the daylight.',
    eggColors: ['#f6b3c8', '#f7e27a'],
  },
  {
    id: 'glimmerfin', name: 'Glimmerfin', traits: ['Fish', 'Tide'], rarity: 'common',
    activity: 'any', movement: 'swim', origin: 'wild',
    blurb: 'Catches light in its scales and lets it out slowly.',
    hint: 'It will never walk to you. Meet it at the water.',
    eggColors: ['#7cc7e8', '#e9f7ff'],
  },
  {
    id: 'puffwren', name: 'Puffwren', traits: ['Bird', 'Grove'], rarity: 'common',
    activity: 'day', movement: 'hop', origin: 'wild',
    blurb: 'Mostly fluff. Puffs up to twice its size when surprised.',
    hint: 'A round little singer of the morning woods.',
    eggColors: ['#f0d9b5', '#b9784f'],
  },
  {
    id: 'vinecoil', name: 'Vinecoil', traits: ['Reptile', 'Grove'], rarity: 'uncommon',
    activity: 'any', movement: 'slither', origin: 'wild',
    blurb: 'Often mistaken for a vine. It finds this hilarious.',
    hint: 'Hides among the forest greens. Patience helps.',
    eggColors: ['#5fa35a', '#d7e86a'],
  },
  {
    id: 'burrowbun', name: 'Burrowbun', traits: ['Mammal', 'Grove', 'Bloom'], rarity: 'common',
    activity: 'day', movement: 'hop', origin: 'wild',
    blurb: 'Wears a flower it found. Will fight you for it, gently.',
    hint: 'Fond of both forest and flowers.',
    eggColors: ['#f3e6d8', '#e7a6b9'],
  },
  {
    id: 'capling', name: 'Capling', traits: ['Fungus', 'Grove'], rarity: 'uncommon',
    activity: 'night', movement: 'waddle', origin: 'wild',
    blurb: 'By day it is just a mushroom. Probably.',
    hint: 'Some mushrooms in the forest only wake at night.',
    eggColors: ['#e0574b', '#fff3e6'],
  },
  {
    id: 'fernkit', name: 'Fernkit', traits: ['Mammal', 'Grove', 'Mystic'], rarity: 'uncommon',
    activity: 'night', movement: 'walk', origin: 'wild',
    blurb: 'The fern on its tail glows when it dreams.',
    hint: 'A shy forest creature with a touch of magic. Nocturnal.',
    eggColors: ['#e58b4c', '#7ccf7a'],
  },
  {
    id: 'duskmoth', name: 'Duskmoth', traits: ['Insect', 'Mystic'], rarity: 'uncommon',
    activity: 'night', movement: 'fly', origin: 'wild',
    blurb: 'The eyes on its wings watch things you cannot see.',
    hint: 'Flutters toward strange scents after sundown.',
    eggColors: ['#6a5596', '#e8c66a'],
  },
  {
    id: 'lumewisp', name: 'Lumewisp', traits: ['Spirit', 'Mystic'], rarity: 'rare',
    activity: 'night', movement: 'float', origin: 'wild',
    blurb: 'Nobody is sure if it is alive. It seems sure.',
    hint: 'Only the most mystical scents reach it, and only in the dark.',
    eggColors: ['#bfe9ff', '#ffffff'],
  },
  {
    id: 'sunscale', name: 'Sunscale', traits: ['Reptile', 'Grove', 'Sand'], rarity: 'common',
    activity: 'day', movement: 'walk', origin: 'wild',
    blurb: 'Basks on warm stones. Its frill pops open when it gets excited.',
    hint: 'A sun-loving lizard that wanders in from the forest edge.',
    eggColors: ['#ffd36a', '#4fb34a'],
  },
  {
    id: 'cinderskink', name: 'Cinderskink', traits: ['Reptile', 'Ember'], rarity: 'common',
    activity: 'any', movement: 'walk', origin: 'wild',
    blurb: 'Its scales glow like coals. Very warm to hug, if it lets you.',
    hint: 'A lizard that loves heat. Look somewhere volcanic.',
    eggColors: ['#3a2e2e', '#ff7a2a'],
  },
  {
    id: 'emberdrake', name: 'Emberdrake', traits: ['Dragon', 'Reptile', 'Ember'], rarity: 'rare',
    activity: 'night', movement: 'fly', origin: 'wild',
    blurb: 'A pocket-sized dragon. Hoards shiny pebbles and sneezes sparks.',
    hint: 'Something with wings nests in the volcano. It only comes out after dark.',
    eggColors: ['#c8402a', '#ffc83d'],
  },
  {
    id: 'coralpuff', name: 'Coralpuff', traits: ['Fish', 'Reef'], rarity: 'common',
    activity: 'any', movement: 'swim', origin: 'wild',
    blurb: 'Puffs up into a perfect ball when startled. It is startled often.',
    hint: 'A round little fish that lives among coral.',
    eggColors: ['#ffb36a', '#ffffff'],
  },
  {
    id: 'driftjelly', name: 'Driftjelly', traits: ['Spirit', 'Reef'], rarity: 'uncommon',
    activity: 'night', movement: 'float', origin: 'wild',
    blurb: 'Floats through the air as if it were water, glowing softly.',
    hint: 'Something glows over the lagoon at night.',
    eggColors: ['#c9a6ff', '#7fe8ff'],
  },
  {
    id: 'axolotl', name: 'Axolotl', traits: ['Amphibian', 'Reef', 'Tide'], rarity: 'legendary',
    activity: 'any', movement: 'waddle', origin: 'wild',
    blurb: 'Always smiling. Nobody knows what it knows. The keeper of every sanctuary.',
    hint: 'A legendary smile lives somewhere in the water. Very, very rarely seen.',
    eggColors: ['#ffb3d0', '#ff6fa8'],
  },
  // ---- hybrids: only from eggs
  {
    id: 'lilyhop', name: 'Lilyhop', traits: ['Amphibian', 'Bloom', 'Tide'], rarity: 'uncommon',
    activity: 'day', movement: 'hop', origin: 'hybrid',
    blurb: 'Wears a lily pad like a hat. Blooms when happy.',
    hint: 'What if a creature of the pond met a creature of flowers?',
    eggColors: ['#f5c2d6', '#8fd18a'],
  },
  {
    id: 'shellshroom', name: 'Shellshroom', traits: ['Reptile', 'Fungus', 'Grove'], rarity: 'uncommon',
    activity: 'any', movement: 'walk', origin: 'hybrid',
    blurb: 'A whole forest floor travels on its back.',
    hint: 'Slow scales and soft spores might get along.',
    eggColors: ['#8b9a6a', '#e0574b'],
  },
  {
    id: 'moonmoth', name: 'Moonmoth', traits: ['Insect', 'Mystic', 'Lunar'], rarity: 'rare',
    activity: 'night', movement: 'fly', origin: 'hybrid',
    blurb: 'Its wings hold a little of the eclipse forever.',
    hint: 'Wings that have touched the moon...',
    eggColors: ['#cfd8ff', '#8f8fd6'],
  },
  {
    id: 'thunderwren', name: 'Thunderwren', traits: ['Bird', 'Grove', 'Storm'], rarity: 'rare',
    activity: 'day', movement: 'hop', origin: 'hybrid',
    blurb: 'Its song is followed by a tiny clap of thunder.',
    hint: 'A singer charged by the storm.',
    eggColors: ['#3c4a6b', '#ffe066'],
  },
  {
    id: 'starkoi', name: 'Starkoi', traits: ['Fish', 'Tide', 'Mystic'], rarity: 'rare',
    activity: 'any', movement: 'swim', origin: 'hybrid',
    blurb: 'Reflects a night sky even at noon.',
    hint: 'A swimmer with something mystical in its blood.',
    eggColors: ['#1f2f6b', '#ffe9a8'],
  },
  {
    id: 'nimbuwhale', name: 'Nimbuwhale', traits: ['Spirit', 'Tide', 'Storm'], rarity: 'legendary',
    activity: 'any', movement: 'float', origin: 'hybrid',
    blurb: 'A tiny whale that swims through the air, trailing weather.',
    hint: 'Spirit, water and storm, all at once. Has anyone seen one?',
    eggColors: ['#eef4ff', '#9bb6e8'],
  },
  {
    id: 'starwyrm', name: 'Starwyrm', traits: ['Dragon', 'Mystic', 'Starlit'], rarity: 'legendary',
    activity: 'night', movement: 'fly', origin: 'hybrid',
    blurb: 'A dragon made of the night sky. Every scale holds a star.',
    hint: 'What would a dragon become if a falling star touched it?',
    eggColors: ['#1e2468', '#fff1a8'],
  },
  // ---- monkeys and kin
  {
    id: 'mossmonkey', name: 'Mossmonkey', traits: ['Primate', 'Grove'], rarity: 'common',
    activity: 'day', movement: 'walk', origin: 'wild',
    blurb: 'Swings from branch to branch and steals your hat. Gives it back, mostly.',
    hint: 'Something cheeky chatters in the forest canopy by day.',
    eggColors: ['#a0703e', '#8fd06a'],
  },
  {
    id: 'lanternlemur', name: 'Lanternlemur', traits: ['Primate', 'Mystic', 'Grove'], rarity: 'uncommon',
    activity: 'night', movement: 'walk', origin: 'wild',
    blurb: 'Its huge eyes glow like lanterns. It uses them to read bedtime stories.',
    hint: 'Two little lights watch the forest after dark. Something strange might tempt them.',
    eggColors: ['#9a96b0', '#ffd86a'],
  },
  {
    id: 'cindermonk', name: 'Cindermonk', traits: ['Primate', 'Ember'], rarity: 'rare',
    activity: 'day', movement: 'walk', origin: 'wild',
    blurb: 'A tiny fire monkey with a tail like a sparkler. Very proud of it.',
    hint: 'A warm, mischievous shape is sometimes seen near the lava.',
    eggColors: ['#c8502a', '#ffd23d'],
  },
  // ---- Sunny Shore
  {
    id: 'flamingle', name: 'Flamingle', traits: ['Bird', 'Shore'], rarity: 'common',
    activity: 'day', movement: 'walk', origin: 'wild',
    blurb: 'Stands on one leg for hours. Nobody has ever seen it switch.',
    hint: 'A pink shape stands very still by the sea.',
    eggColors: ['#ff9ec4', '#ffffff'],
  },
  {
    id: 'pouchbill', name: 'Pouchbill', traits: ['Bird', 'Shore', 'Tide'], rarity: 'common',
    activity: 'day', movement: 'waddle', origin: 'wild',
    blurb: 'Keeps a snack, a shell and a very surprised crab in its pouch.',
    hint: 'A big beak waddles along the tideline.',
    eggColors: ['#f4efe4', '#ffb84d'],
  },
  {
    id: 'mistheron', name: 'Mistheron', traits: ['Bird', 'Tide', 'Mystic'], rarity: 'uncommon',
    activity: 'any', movement: 'walk', origin: 'hybrid',
    blurb: 'Steps out of the sea fog without a sound, and back into it.',
    hint: 'Shore birds who share the tide might raise something misty.',
    eggColors: ['#c8d8e8', '#7a8ab0'],
  },
  // ---- Dune Hollow
  {
    id: 'sandpincer', name: 'Sandpincer', traits: ['Arachnid', 'Sand'], rarity: 'common',
    activity: 'night', movement: 'scuttle', origin: 'wild',
    blurb: 'Waves its claws to say hello. Its tail is only for show. Probably.',
    hint: 'Something clicks across the dunes at night.',
    eggColors: ['#e0a850', '#7a4a2a'],
  },
  {
    id: 'dunecoil', name: 'Dunecoil', traits: ['Reptile', 'Sand'], rarity: 'common',
    activity: 'day', movement: 'slither', origin: 'wild',
    blurb: 'Sidewinds across hot sand, leaving tidy little S shapes behind.',
    hint: 'Strange S-shaped tracks cross the warm sand.',
    eggColors: ['#e8c890', '#b07a3a'],
  },
  {
    id: 'sunhood', name: 'Sunhood', traits: ['Reptile', 'Sand', 'Mystic'], rarity: 'rare',
    activity: 'day', movement: 'slither', origin: 'hybrid',
    blurb: 'When it spreads its hood, a golden sun shines on it. It loves an audience.',
    hint: 'Desert creatures with claws and scales might share a sunny secret.',
    eggColors: ['#f2c46a', '#ff7a2a'],
  },
  // ---- Mythical: found only in special moments
  {
    id: 'cloudserpent', name: 'Cloud Serpent', traits: ['Dragon', 'Spirit', 'Storm'], rarity: 'mythical',
    activity: 'any', movement: 'float', origin: 'hybrid',
    blurb: 'A long sky dragon that rides the thunder. It grants one wish a year, but only small ones.',
    hint: 'Two dragons, and thunder overhead.',
    eggColors: ['#3aa86a', '#ffd23d'],
  },
  {
    id: 'phoenix', name: 'Phoenix', traits: ['Bird', 'Ember', 'Spirit'], rarity: 'mythical',
    activity: 'any', movement: 'fly', origin: 'hybrid',
    blurb: 'Burns bright, then rests as embers, then rises again. It is never sad about it.',
    hint: 'A bird and a creature of fire, kindred under a darkened sun.',
    eggColors: ['#ff5a2a', '#ffd23d'],
  },
  {
    id: 'kraken', name: 'Kraken', traits: ['Reef', 'Tide', 'Spirit'], rarity: 'mythical',
    activity: 'night', movement: 'swim', origin: 'wild', onlyDuring: 'fullmoon', onlyAt: ['reef'],
    blurb: 'Far smaller than the stories say. Far friendlier too. Hugs with all eight arms.',
    hint: 'Something stirs beneath the coral when the moon is full.',
    eggColors: ['#7a4ad0', '#ff8fc8'],
  },
  {
    id: 'qilin', name: 'Qilin', traits: ['Dragon', 'Mammal', 'Mystic'], rarity: 'mythical',
    activity: 'any', movement: 'walk', origin: 'hybrid',
    blurb: 'Walks so gently that flowers bloom in its hoofprints.',
    hint: 'A dragon and a gentle magical creature, beneath a sky full of falling stars.',
    eggColors: ['#7fd6c8', '#ffd86a'],
  },
  // ---- Wave 2: one or two new friends for every world, plus two mythicals
  {
    id: 'hedgehum', name: 'Hedgehum', traits: ['Mammal', 'Grove', 'Bloom'], rarity: 'common',
    activity: 'day', movement: 'scuttle', origin: 'wild',
    blurb: 'Hums while it naps. Petals get stuck in its spines and it wears them proudly.',
    hint: 'A prickly little hummer among the flowers.',
    eggColors: ['#b08a64', '#f7c6d6'],
  },
  {
    id: 'magmole', name: 'Magmole', traits: ['Mammal', 'Ember'], rarity: 'common',
    activity: 'any', movement: 'waddle', origin: 'wild',
    blurb: 'Tunnels through warm rock. Its nose glows brighter the deeper it digs.',
    hint: 'Something digs near the lava, nose first.',
    eggColors: ['#5a4a52', '#ff8a3a'],
  },
  {
    id: 'ashowl', name: 'Ashowl', traits: ['Bird', 'Ember', 'Mystic'], rarity: 'uncommon',
    activity: 'night', movement: 'fly', origin: 'wild',
    blurb: 'Its feathers are soft as ash and warm as a hearth. Hoots in little sparks.',
    hint: 'A wise bird of the volcano, awake after dark.',
    eggColors: ['#6a6670', '#ffb04a'],
  },
  {
    id: 'bubblecrab', name: 'Bubblecrab', traits: ['Reef', 'Shore'], rarity: 'common',
    activity: 'any', movement: 'scuttle', origin: 'wild',
    blurb: 'Blows a bubble when it is happy, which is always.',
    hint: 'A sideways walker of the reef and sand.',
    eggColors: ['#ff7a5a', '#ffe0c8'],
  },
  {
    id: 'glidemanta', name: 'Glidemanta', traits: ['Fish', 'Reef', 'Spirit'], rarity: 'rare',
    activity: 'any', movement: 'swim', origin: 'wild',
    blurb: 'Glides through the water like a kite on the wind. Loves a gentle current.',
    hint: 'A graceful glider of the deep reef. Meet it at the water.',
    eggColors: ['#3a5aa8', '#bfe8ff'],
  },
  {
    id: 'sandotter', name: 'Sandotter', traits: ['Mammal', 'Shore', 'Tide'], rarity: 'uncommon',
    activity: 'day', movement: 'waddle', origin: 'wild',
    blurb: 'Keeps a favourite pebble in its pocket and shows it to everyone.',
    hint: 'A playful swimmer that loves the beach in the sun.',
    eggColors: ['#a8784e', '#f2dcc0'],
  },
  {
    id: 'conchsnail', name: 'Conchsnail', traits: ['Shore', 'Reef'], rarity: 'common',
    activity: 'any', movement: 'waddle', origin: 'wild',
    blurb: 'Hold its shell to your ear and you can hear it humming the sea.',
    hint: 'A slow traveller where the shore meets the reef.',
    eggColors: ['#f7b8a0', '#fff1e0'],
  },
  {
    id: 'dunefox', name: 'Dunefox', traits: ['Mammal', 'Sand'], rarity: 'uncommon',
    activity: 'night', movement: 'walk', origin: 'wild',
    blurb: 'Its huge ears can hear a beetle sneeze three dunes away.',
    hint: 'A big-eared wanderer of the desert night.',
    eggColors: ['#f0c88a', '#fff6e4'],
  },
  {
    id: 'aurorastag', name: 'Aurora Stag', traits: ['Mammal', 'Spirit', 'Mystic'], rarity: 'mythical',
    activity: 'any', movement: 'walk', origin: 'hybrid',
    blurb: 'Its antlers hold the northern lights. Where it sleeps, the snow glows.',
    hint: 'A furry creature and a spirit, kindred beneath dancing sky lights.',
    eggColors: ['#5affc0', '#8a7aff'],
  },
  {
    id: 'prismkoi', name: 'Prism Koi', traits: ['Fish', 'Tide', 'Bloom'], rarity: 'mythical',
    activity: 'any', movement: 'swim', origin: 'wild', onlyDuring: 'rainbow', onlyAt: ['pond'],
    blurb: 'Swims up the rainbow when it rains and back down when it stops. Every scale is a different colour.',
    hint: 'Something shimmers in the pond, but only under a rainbow.',
    eggColors: ['#ff6a8a', '#6ad8ff'],
  },
  // ---- Cloud Isle
  {
    id: 'cloudlamb', name: 'Cloudlamb', traits: ['Mammal', 'Sky'], rarity: 'common',
    activity: 'day', movement: 'hop', origin: 'wild',
    blurb: 'Its wool is a real cloud. On hot days it rains on itself, just a little.',
    hint: 'A fluffy hopper that lives up where the breeze blows.',
    eggColors: ['#ffffff', '#bfe0ff'],
  },
  {
    id: 'kitewing', name: 'Kitewing', traits: ['Bird', 'Sky'], rarity: 'common',
    activity: 'day', movement: 'fly', origin: 'wild',
    blurb: 'Flies like a kite, ribbons and all. Never needs a string.',
    hint: 'A bird with a ribbon tail that rides the wind.',
    eggColors: ['#ff7a8a', '#ffe14d'],
  },
  {
    id: 'zephyrwisp', name: 'Zephyrwisp', traits: ['Spirit', 'Sky'], rarity: 'uncommon',
    activity: 'any', movement: 'float', origin: 'wild',
    blurb: 'A little gust that decided to stay. It ruffles your hair to say hello.',
    hint: 'A playful spirit carried on the breeze.',
    eggColors: ['#c8f0ff', '#e8d8ff'],
  },
  {
    id: 'breezedrake', name: 'Breezedrake', traits: ['Dragon', 'Sky'], rarity: 'rare',
    activity: 'day', movement: 'fly', origin: 'wild',
    blurb: 'A small dragon with feathered wings. It sneezes tiny whirlwinds.',
    hint: 'A rare dragon of the high winds. Patience on the cloud tops.',
    eggColors: ['#7ad8c8', '#ffffff'],
  },
  // ---- Level rewards: only from reaching keeper levels (one every 5)
  {
    id: 'jackalope', name: 'Jackalope', traits: ['Mammal', 'Grove', 'Mystic'], rarity: 'legendary',
    activity: 'day', movement: 'hop', origin: 'reward',
    blurb: 'A bunny with tiny antlers. It insists they are perfectly normal.',
    hint: 'A gift for reaching keeper level 5.', eggColors: ['#d8b88a', '#8a6a4a'],
  },
  {
    id: 'kitsune', name: 'Kitsune', traits: ['Mammal', 'Mystic', 'Spirit'], rarity: 'legendary',
    activity: 'night', movement: 'walk', origin: 'reward',
    blurb: 'A clever fox spirit. It grows a new tail every hundred years, and is very proud of each one.',
    hint: 'A gift for reaching keeper level 10.', eggColors: ['#ff9a4a', '#ffffff'],
  },
  {
    id: 'flyingsnake', name: 'Flying Snake', traits: ['Reptile', 'Spirit', 'Bloom'], rarity: 'legendary',
    activity: 'day', movement: 'float', origin: 'reward',
    blurb: 'A feathered serpent that glides on warm air, humming as it goes.',
    hint: 'A gift for reaching keeper level 15.', eggColors: ['#5fd0a0', '#ffd23d'],
  },
  {
    id: 'pegasus', name: 'Pegasus', traits: ['Mammal', 'Spirit', 'Bird'], rarity: 'legendary',
    activity: 'day', movement: 'fly', origin: 'reward',
    blurb: 'A winged horse. It gallops on clouds and lands without a sound.',
    hint: 'A gift for reaching keeper level 20.', eggColors: ['#ffffff', '#a8d8ff'],
  },
  {
    id: 'griffin', name: 'Griffin', traits: ['Bird', 'Mammal', 'Ember'], rarity: 'legendary',
    activity: 'day', movement: 'walk', origin: 'reward',
    blurb: 'Half eagle, half lion, all heart. Guards anything shiny it finds.',
    hint: 'A gift for reaching keeper level 25.', eggColors: ['#c89a4a', '#ffffff'],
  },
  {
    id: 'hippocampus', name: 'Hippocampus', traits: ['Fish', 'Mammal', 'Tide'], rarity: 'legendary',
    activity: 'any', movement: 'swim', origin: 'reward',
    blurb: 'A sea horse in the grandest sense: a horse in front, a fish behind.',
    hint: 'A gift for reaching keeper level 30.', eggColors: ['#3ac8c8', '#a8ffe8'],
  },
  {
    id: 'thunderbird', name: 'Thunderbird', traits: ['Bird', 'Spirit', 'Storm'], rarity: 'legendary',
    activity: 'any', movement: 'fly', origin: 'reward',
    blurb: 'When it beats its great wings, the sky rumbles. Politely.',
    hint: 'A gift for reaching keeper level 35.', eggColors: ['#2a3a7a', '#ffd83d'],
  },
  {
    id: 'baku', name: 'Baku', traits: ['Mammal', 'Mystic', 'Spirit'], rarity: 'legendary',
    activity: 'night', movement: 'walk', origin: 'reward',
    blurb: 'A dream tapir. It nibbles bad dreams away and leaves the good ones.',
    hint: 'A gift for reaching keeper level 40.', eggColors: ['#2a2a3a', '#f4f0ff'],
  },
  {
    id: 'sphinx', name: 'Sphinx', traits: ['Mammal', 'Sand', 'Mystic'], rarity: 'legendary',
    activity: 'day', movement: 'walk', origin: 'reward',
    blurb: 'A regal cat who asks riddles. It always lets you win.',
    hint: 'A gift for reaching keeper level 45.', eggColors: ['#e8c070', '#3a6ad0'],
  },
  {
    id: 'unicorn', name: 'Unicorn', traits: ['Mammal', 'Mystic', 'Bloom'], rarity: 'mythical',
    activity: 'any', movement: 'walk', origin: 'reward',
    blurb: 'The rarest friend of all. Flowers turn toward it as it passes.',
    hint: 'A gift for reaching keeper level 50.', eggColors: ['#ffffff', '#ff9ee8'],
  },
  // ---- Star Keeper rewards: one every 10 levels from 60 to 100
  // ---- newer wild friends
  {
    id: 'sunmane', name: 'Sunmane Lion', traits: ['Mammal', 'Sand'], rarity: 'rare',
    activity: 'day', movement: 'walk', origin: 'wild',
    blurb: 'Its golden mane catches the sunlight. Roars very politely, then naps for hours.',
    hint: 'Something proud dozes in the warm sand. A Sunbaked Lure might wake it.',
    eggColors: ['#e8b44a', '#a8602a'],
  },
  {
    id: 'embertiger', name: 'Ember Tiger', traits: ['Mammal', 'Ember'], rarity: 'rare',
    activity: 'any', movement: 'walk', origin: 'wild',
    blurb: 'Its stripes glow like coals when it purrs. Loves a warm rock and a long stretch.',
    hint: 'Striped and fiery. It prowls where the ground is warm.',
    eggColors: ['#ff8a2a', '#2a1a1a'],
  },
  {
    id: 'mossyphant', name: 'Mossyphant', traits: ['Mammal', 'Grove'], rarity: 'uncommon',
    activity: 'day', movement: 'walk', origin: 'wild',
    blurb: 'A little elephant with moss on its back. Waters the flowers with its trunk.',
    hint: 'Big ears, small footsteps, somewhere in the forest.',
    eggColors: ['#9aa8a0', '#6fbf5a'],
  },
  {
    id: 'bamboopanda', name: 'Bamboo Panda', traits: ['Mammal', 'Bloom', 'Grove'], rarity: 'uncommon',
    activity: 'day', movement: 'walk', origin: 'wild',
    blurb: 'Eats, rolls over, eats again. A professional at being cozy.',
    hint: 'It loves anything sweet and leafy. Try something that smells of flowers.',
    eggColors: ['#ffffff', '#2a2a2a'],
  },
  {
    id: 'waddlefin', name: 'Waddlefin', traits: ['Bird', 'Shore', 'Tide'], rarity: 'common',
    activity: 'day', movement: 'waddle', origin: 'wild',
    blurb: 'A little penguin that slides on its belly whenever nobody is looking.',
    hint: 'Waddles along the tide line. Salty smells bring it in.',
    eggColors: ['#2a3a5a', '#ffffff'],
  },
  {
    id: 'duskbat', name: 'Duskbat', traits: ['Mammal', 'Mystic', 'Spirit'], rarity: 'uncommon',
    activity: 'night', movement: 'fly', origin: 'wild',
    blurb: 'Hangs upside down to think. Squeaks a happy song when it finds a moth to chat with.',
    hint: 'Something flutters about after dark, drawn to secrets.',
    eggColors: ['#4a3a6a', '#ffd21a'],
  },
  {
    id: 'moonrabbit', name: 'Moon Rabbit', traits: ['Mammal', 'Mystic', 'Spirit'], rarity: 'legendary',
    activity: 'night', movement: 'hop', origin: 'reward',
    blurb: 'Lives on the moon and visits on clear nights. Makes the softest rice cakes you ever tasted.',
    hint: 'A gift for reaching keeper level 60.', eggColors: ['#e8e4ff', '#ffe680'],
  },
  {
    id: 'tanuki', name: 'Tanuki', traits: ['Mammal', 'Grove', 'Mystic'], rarity: 'legendary',
    activity: 'any', movement: 'walk', origin: 'reward',
    blurb: 'Puts a leaf on its head to change shape. Usually it changes into a slightly different tanuki.',
    hint: 'A gift for reaching keeper level 70.', eggColors: ['#8a6a4a', '#5fbf5a'],
  },
  {
    id: 'shisa', name: 'Shisa', traits: ['Mammal', 'Ember', 'Spirit'], rarity: 'legendary',
    activity: 'day', movement: 'walk', origin: 'reward',
    blurb: 'A lion-dog guardian. One roar keeps bad luck away for a whole year.',
    hint: 'A gift for reaching keeper level 80.', eggColors: ['#e8a03a', '#d8483e'],
  },
  {
    id: 'leviathan', name: 'Leviathan', traits: ['Dragon', 'Reef', 'Tide'], rarity: 'legendary',
    activity: 'any', movement: 'swim', origin: 'reward',
    blurb: 'A sea dragon from the deepest blue. Gives rides to lost fish and sings them home.',
    hint: 'A gift for reaching keeper level 90.', eggColors: ['#1a6a9a', '#7affe0'],
  },
  {
    id: 'worldturtle', name: 'World Turtle', traits: ['Reptile', 'Grove', 'Spirit'], rarity: 'mythical',
    activity: 'any', movement: 'walk', origin: 'reward',
    blurb: 'Carries a whole tiny island on its back, trees and all. Very old, very wise, very slow.',
    hint: 'A gift for reaching keeper level 100.', eggColors: ['#5fa35a', '#c8b88a'],
  },
];

export const SPECIES_BY_ID: Record<string, SpeciesDef> = Object.fromEntries(SPECIES.map((s) => [s.id, s]));
export const WILD_SPECIES = SPECIES.filter((s) => s.origin === 'wild');

export function species(id: string): SpeciesDef {
  const s = SPECIES_BY_ID[id];
  if (!s) throw new Error(`Unknown species ${id}`);
  return s;
}
